# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ef112673a86cecb3a93a58804413c8ac9be40e461a27a2bc326eaa0f76124af408f105a3b6bd0b5d8d35526a6fd90ebe2b6c90c39914c5852b1e2a6181a9f29

test:
  secret_key_base: fc23b51a3d8745b8ed9a123c10f02fb83bc6942792bd40b6eb7f411570b34b8e9affc036bca0c130a67e78fd7085604dabc2796afbf98b9faa01f359accfa784

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
